# .github/workflows/main.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  first-workflow:
    uses: palash150403/test/.github/workflows/w1.yml@main
    with:
      some_input: "value_for_first_workflow"

  second-workflow:
    runs-on: ubuntu-latest
    needs: first-workflow
    steps:
      - name: Call second reusable workflow (w2.yml)
        uses: palash150403/test/.github/workflows/w2.yml@main
        with:
          MY_VARIABLE: ${{ needs.first-workflow.outputs.MY_VARIABLE }}
