name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  first-workflow:
    uses: palash150403/test/.github/workflows/w1.yml@main
    with:
      some_input: "value_for_first_workflow"

  second-workflow:
    needs: first-workflow
    uses: palash150403/test/.github/workflows/w2.yml@main
    with:
      some_input: "value_for_second_workflow"
      MY_VARIABLE: ${{ needs.first-workflow.outputs.MY_VARIABLE }}
