# main.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-1:
    uses: palash150403/test/.github/workflows/w1.yml@main
    with:
      some_input: "input_value"

  call-workflow-2:
    uses: palash150403/test/.github/workflows/w2.yml@main
    with:
      some_input: "input_value"
    needs: call-workflow-1  
