# main.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-1:
    uses: ./w1.yml
    with:
      some_input: "input_value"

  call-workflow-2:
    uses: ./w2.yml
    with:
      some_input: "input_value"
    needs: call-workflow-1  # This ensures workflow-1 is completed before calling workflow-2
