name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-1:
    runs-on: ubuntu-latest
    steps:
      - name: Call Workflow 1 to generate the environment variable
        id: workflow1
        uses: palash150403/test/.github/workflows/w1.yml@main
        with:
          example_input: "Some input value"

  call-workflow-2:
    runs-on: ubuntu-latest
    needs: call-workflow-1
    steps:
      - name: Call Workflow 2 and pass the environment variable from Workflow 1
        id: workflow2
        uses: palash150403/test/.github/workflows/w2.yml@main
        with:
          my_env_variable: ${{ needs.call-workflow-1.outputs.my_env_variable }}


# # main.yml (Main Workflow)
# name: Main Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   call-workflow-1:
#     uses: palash150403/test/.github/workflows/w1.yml@main
#     with:
#       some_input: "input_value"
  
#   call-workflow-2:
#     needs: call-workflow-1  # Ensure this runs after call-workflow-1
#     uses: palash150403/test/.github/workflows/w2.yml@main
#     with:
#       some_input: ${{ needs.call-workflow-1.outputs.my_output }}  # Pass output from w1 to w2
