name: Reusable Workflow 1

on:
  workflow_call:
    inputs:
      some_input:
        required: true
        type: string

jobs:
  set-environment-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set a variable in GITHUB_ENV
        run: echo "MY_VARIABLE=some_value" >> $GITHUB_ENV

      - name: Other steps
        run: |
          echo "Running additional steps"






# # w1.yml (Reusable Workflow 1)
# name: Reusable Workflow 1

# on:
#   workflow_call:
#     inputs:
#       some_input:
#         required: true
#         type: string

# jobs:
#   set-output:
#     runs-on: ubuntu-latest
#     outputs:
#       my_output: ${{ steps.set_output.outputs.value }}  # Capture output from the step

#     steps:
#       - name: Set output value
#         id: set_output
#         run: |
#           echo "value=some_generated_value" >> $GITHUB_OUTPUT  # Set the output value
