name: Reusable Workflow 1

on:
  workflow_call:
    outputs:
      MY_VARIABLE:
        value: ${{ jobs.set-output.outputs.MY_VARIABLE }}
        

jobs:
  set-output:
    runs-on: ubuntu-latest
    outputs:
      MY_VARIABLE: ${{ steps.set_output.outputs.MY_VARIABLE }}
    steps:
      - name: Set output using GITHUB_OUTPUT
        id: set_output
        run: echo "MY_VARIABLE=wf1-val" >> $GITHUB_OUTPUT
          
      - name: Debug - Check the output
        run: echo "The output MY_VARIABLE is ${{ steps.set_output.outputs.MY_VARIABLE }}"


      - name: app_version
        shell: bash
        run: |
          app_version="1.1.1"          
          if [[ "${{ github.ref }}" == "refs/heads/integration" || "${{ github.ref }}" == refs/heads/feature* ]]; then
            echo "VERSION $app_version"
            echo "VERSION=$app_version" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "VERSION $app_version"
            echo "VERSION=$app_version" >> $GITHUB_ENV
          else
            echo "Branch not relevant for versioning."
          fi
      
