name: Reusable Workflow 2

on:
  workflow_call:
    inputs:
      some_input:
        required: true
        type: string

jobs:
  use-output:
    runs-on: ubuntu-latest
    steps:
      - name: Use the output from the first workflow
        run: echo "The value of MY_VARIABLE is ${{ inputs.MY_VARIABLE }}"
