name: Reusable Workflow 2

on:
  workflow_call:
    inputs:
      some_input:
        required: true
        type: string

jobs:
  use-output:
    runs-on: ubuntu-latest
    needs: workflow-1  # Ensure workflow-1 is completed before running
    steps:
      - name: Use output from workflow-1
        run: |
          echo "Received value from workflow-1: ${{ needs.workflow-1.outputs.my_output }}"
