name: Reusable Workflow 2

on:
  workflow_call:
    inputs:
      MY_VARIABLE:
        required: true
        type: string

jobs:
  print-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Print the passed value of MY_VARIABLE
        run: echo "The value of MY_VARIABLE is ${{ inputs.MY_VARIABLE }}"
