name: Reusable Workflow 2

on:
  workflow_call:
    inputs:
      some_input:
        required: true
        type: string

jobs:
  use-environment-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Access environment variable
        run: echo "The value of MY_VARIABLE is $MY_VARIABLE"




# # w2.yml (Reusable Workflow 2)
# name: Reusable Workflow 2

# on:
#   workflow_call:
#     inputs:
#       some_input:
#         required: true
#         type: string

# jobs:
#   use-output:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Use input from workflow-1
#         run: |
#           echo "Received value from workflow-1: ${{ inputs.some_input }}"
